name: Call Docs-storage webhook on PR Merge

on:
  pull_request:
    types:
      - closed  # Detecta cuando se cierra una PR

jobs:
  call-api:
    if: github.event.pull_request.merged == true  # Asegura que fue merge y no simplemente cerrada
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook to Docs-storage
        run: |
          curl -X POST https://0a21-2a0c-5a85-6305-4d00-10d5-a478-4c1e-b5b2.ngrok-free.app/webhook/github \
               -H "Content-Type: application/json" \
               -d '{"message": "PR merged: ${{ github.event.pull_request.title }}"}'
