name: Call Docs-storage webhook on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  call-api:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Extract operation id from PR label
        id: extract_operation_id
        run: |
          LABELS=$(echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r '.[].name')
          echo "Labels: $LABELS"

          for label in $LABELS; do
            if [[ "$label" == docs/outline#* ]]; then
              OPERATION_ID="${label#docs/outline#}"
              echo "Found OPERATION ID: $OPERATION_ID"
              echo "OPERATION_ID=$OPERATION_ID" >> $GITHUB_OUTPUT
              break
            fi
          done

      - name: Send webhook to Docs-storage
        if: steps.extract_operation_id.outputs.OPERATION_ID != ''
        run: |
          curl -X POST "${{ vars.DOCS_STORAGE_WEBHOOK_URL }}" \
               -H "Content-Type: application/json" \
               -d '{
                 "message": "PR merged: ${{ github.event.pull_request.title }}",
                 "operation_id": "${{ steps.extract_collection_id.outputs.OPERATION_ID }}",
                 "event": "pull_request"
               }'
