name: Call Docs-storage webhook on PR Merge

on:
  pull_request:
    types:
      - closed  # Trigger when a Pull Request is closed

jobs:
  call-api:
    if: github.event.pull_request.merged == true  # Only run if PR was merged
    runs-on: ubuntu-latest

    steps:
      - name: Extract collection_id from PR label
        id: extract_collection_id
        run: |
          LABELS=$(echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r '.[].name')
          echo "Labels: $LABELS"

          for label in $LABELS; do
            if [[ "$label" == docs/outline#* ]]; then
              COLLECTION_ID="${label#docs/outline#}"
              echo "Found collection ID: $COLLECTION_ID"
              echo "COLLECTION_ID=$COLLECTION_ID" >> $GITHUB_OUTPUT
              break
            fi
          done

      - name: Send webhook to Docs-storage
        if: steps.extract_collection_id.outputs.COLLECTION_ID != ''
        run: |
          curl -X POST https://f1ff-2a0c-5a85-6305-4d00-102-8b69-d3f8-15e1.ngrok-free.app/webhooks/github \
               -H "Content-Type: application/json" \
               -d '{
                 "message": "PR merged: ${{ github.event.pull_request.title }}",
                 "coll
