name: Validate Documentation Source

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - '**/*.md'
      - 'docs/**'

jobs:
  validate-docs-source:
    name: Validate Documentation Source
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate documentation source
        run: |
          # Check if PR is from Outline
          FULL_TEXT="${{ github.event.pull_request.title }} ${{ github.event.pull_request.body }}"
          
          if echo "$FULL_TEXT" | grep -qiE "(collection.*#|for collection|Update documentation for collection|operation_id|from Outline)"; then
            echo "✓ PR appears to be from Outline"
            IS_FROM_OUTLINE=true
          else
            echo "✗ PR does not appear to be from Outline"
            IS_FROM_OUTLINE=false
          fi
          
          # Get changed files using GitHub API data (more reliable for PRs)
          echo "Files changed in this PR:"
          CHANGED_FILES=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files --jq '.[].filename')
          echo "$CHANGED_FILES"
          
          # Check for documentation changes (excluding README.md)
          if echo "$CHANGED_FILES" | grep -qE '\.(md)$|^docs/' | grep -v '^README\.md
            echo "Documentation files were modified"
            
            if [ "$IS_FROM_OUTLINE" = "false" ]; then
              echo "::error::Documentation changes must come from Outline"
              echo "Please ensure documentation changes are made through Outline and not directly in the repository."
              exit 1
            else
              echo "✓ Documentation changes are from Outline - validation passed"
            fi
          else
            echo "No documentation files were modified"
          fi
        env:
          GH_TOKEN: ${{ github.token }}; then
            echo "Documentation files were modified"
            
            if [ "$IS_FROM_OUTLINE" = "false" ]; then
              echo "::error::Documentation changes must come from Outline"
              echo "Please ensure documentation changes are made through Outline and not directly in the repository."
              exit 1
            else
              echo "✓ Documentation changes are from Outline - validation passed"
            fi
          else
            echo "No documentation files were modified"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
